### ISSUE TITLE
cmake builds without any optimization settings on first build (bin folder not constructed)

### ISSUE THREAD

**Issue by Eisverygoodletter** [rm-robotics/ev3dev-cpp-template-wrapper#33]
**Describe the bug**
Inside the lib-building branch 524671b :
Normally cmake should build with the `-Os` flag on so that it optimizes for size, but it doesn't.

**To Reproduce**
1. clone the repository
2. go to the lib-building branch 524671b
3. do `./scripts/compile.sh` to compile
4. See that it tells you the file size is too large
5. do `./scripts/compile.sh` to recompile
6. See that file size is significantly smaller as `-Os` flag is used

**Expected behavior**
`-Os` flag is used on first go

**Additional context**
my suspicions are that modifications need to be made to either in the main `CMakeLists.txt`, or the `runWithinContainer.sh` script

**Comment by txvvgnx** [comment]
Fixed in commit b840e41
