### ISSUE TITLE
`Omni` class revamp checklist

### ISSUE THREAD

**Issue by Eisverygoodletter** [rm-robotics/ev3dev-cpp-template-wrapper#51]
List of stuff the new `Omni` class should achieve
1. simplified constructor
2. less bloat
3. make more assumptions
4. the math should be documented
---
**Space for discussing below** (how to achieve these goals

**Comment by Eisverygoodletter** [comment]
### First thing: what should the constructor look like
A: `Omni(address, address, address, address, iraddress, compassaddress)`
B: `Omni(motorpair, motorpair, irseeker, compass)`
C: `Omni(motorpair, motorpair` (use irseeker and compass as parameters in functions
D: `Omni()` assume port names are standardised to some particular set of rules
E: `Omni(Motor, Motor, Motor, Motor, IrSeeker, Compass)` (drop support for MotorPair)
Which option should we go with?

**Comment by txvvgnx** [comment]
Since Omni robots are often built with two motor pairs that control horizontal and vertical movement (as in, horizontal and vertical movement across a 2D grid), B would still be the option I'd prefer

Besides, the constructors listed only support 4 motors anyway
